name: shenfun_doc_env

channels:
  - conda-forge
  - defaults

dependencies:
  - python
  - pip
  - cython
  - fftw
  - numpy
  - numba
  - sympy
  - pyyaml
  - scipy
  - mpi4py
  - mpi4py-fft
  - plotly
  - Sphinx
  - nbsphinx
  - pip:
    - sphinxcontrib-bibtex
    - sphinx-rtd-theme
    - myst-nb
