name: github-CI

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        python-version: ["3.9", "3.10", "3.11"]
    name: Python ${{ matrix.python-version }} example
    defaults:
      run:
        shell: bash -el {0}
    steps:
    - uses: actions/checkout@v4
    - uses: conda-incubator/setup-miniconda@v3
      with:
          activate-environment: shenfun
          channels: conda-forge
          environment-file: environment.yml
          python-version: ${{ matrix.python-version }}
          auto-activate-base: true
    - run: conda --version
    - run: which python
    - run: python setup.py build_ext -i 
    - run: echo $PYTHONPATH
    - run: export PYTHONPATH=$PWD:$PYTHONPATH
    - run: py.test tests/
    #- run: |
    #    conda config --set always_yes yes
    #    conda install conda-build numpy
    #- run: |
    #    conda env list
    #    conda build ./conf/conda

